##################################################################################
### DiagMC configuration file for the Hubbard model on a finite square lattice ###
##################################################################################

### Diagram parameters for measurement/normalization subspaces ###
diag:
  # The class of measurement diagram(s), chosen from the following:
  # [vacuum, charge_poln, self_en_stat, self_en_dyn]
  diag_type: charge_poln
  subspaces: [0, 3] # V = V_0 \oplus V_n
  norm_space_weight: 0.020008223228745299 # Initial diagram weight D_0 for the normalization subspace V_0
  order: 3 # Order n in perturbation theory for the measurement space V_n
  n_legs: 2 # Number of external legs in the V_n measurement
  n_intn: 2 # (= n - 1) Number of interaction lines in all V_n graphs (order in U)
  n_times: 3 # (= n) One modifiable time per internal line (static U), plus outgoing leg
  n_posns: 3 # (= n) One modifiable position per internal line (local U), plus outgoing leg

### MCMC measurement parameters ###
mcmc:
  debug: false # Debug-level verbosity
  verbose: true # Summarize after every half-millionth measurement
  normalize: true # Should the integration results be normalized?
  save_serial: false # Should the thread results be individually saved?
  use_batch_U: true # Should we perform a batch calculation for each U in U_batch?
  n_warm: 100000 # Number of steps in the burn-in / warmup phase
  n_meas: 50000000 # Total number of steps in the measurement phase (including skips)
  n_skip: 1 # Number of steps to skip in ancy points to measure at
  n_threads: 1 # Number of MPI threads used in the calculation
  n_nu_meas: 5 # Number of external frequency points to measure at
  n_k_meas: 45 # Number of external momentum points in the k-path along which we measure
  max_posn_shift: 3 # Variable maximum step size in local position component shifts
  job_id: 1629109433 # Job ID no. (POSIX integer timestamp) for this MCMC run data
  save_dir: run_1629109433 # Save directory for the run results (default: './run_{job_id}')
  save_name: chi_ch_hub_2dsqlat # Prefix for saved MCMC data

### Physical/lattice parameters ###
phys:
  dim: 2 # Spatial dimensionality of the problem
  n_site: 900  # Total number of lattice sites
  n_site_pd: 30 # Number of lattice sites along a single direction (i.e., L / a)
  n_site_irred: 16   # Cutoff for (BC) 'irreducible' lattice distances
  num_elec: 900  # Number of electrons in the lattice
  lat_const: 1.0 # Hypercubic lattice constant a
  lat_length: 30.0 # Lattice length in Bohr radii
  vol_lat: 900.0  # Volume of the lattice
  # Target (noninteracting) chemical potential. If supplied and target_n0
  # is null, we work at fixed chemical potential and variable density.
  target_mu:
  # Target density in units of the lattice constant; since the number of electrons
  # is coarse-grained, the actual density may differ slightly. If supplied, we work
  # at fixed density and variable chemical potential.
  target_n0: 1.0
  # The HF renormalized, aka reduced chemical potential, is
  # mu_tilde \approx mu - (U n / 2) (exact in the thermodynamic limit);
  # we implement the HF resummation by working as a function of (fixed)
  # reduced chemical potential, i.e., we define G_HF(mu) := G_0(mu_tilde)
  mu_tilde: 0.0009383466467934864
  mu: 0.5009383466467935  # Physical chemical potential corresponding to mu_tilde
  rs: 0.5641895835477563 # Wigner-Seitz radius (for HEG correspondence)
  n0: 1.0 # Initial lattice electron density n0, set to half-filling
  ef: 0.0 # Fermi energy (Hartrees)
  beta: 10.0 # Inverse temperature (1 / eV)
  t_hop: 1.0 # Nearest-neighbor hopping parameter t (Hartrees)
  s_ferm: 0.5 # Fermion spin
  U_loc: 1.0 # Hubbard U (Hartrees)
  # List of U values to use for the (optional) batch-mode calculation
  U_batch: [0.1, 0.5, 1.0, 2.0, 4.0]

### Propagator parameters ###
propr:
  delta_tau: 1.0e-10 # Numerical imaginary time infinitesimal (for tau mesh)
  n_nu: 1024 # (Even) number of bosonic frequency points for uniform FFT mesh
  n_tau: 1024 # (Even) number of im. time points in the logarithmic FFT mesh [0, beta)
  job_id: 1629103724 # Job ID no. for propagator data used in this run
  save_dir: propagators/proprs_1629103724 # Path to propagator data used in this run
